export enum ButtonType {
  Neutral = 'btn-neutral',
  Primary = 'btn-primary',
  Secondary = 'btn-secondary',
  Accent = 'btn-accent',
  Info = 'btn-info',
  Success = 'btn-success',
  Warning = 'btn-warning',
  Error = 'btn-error',
  Outline = 'btn-outline',
  Dash = 'btn-dash',
  Soft = 'btn-soft',
  Ghost = 'btn-ghost',
  Link = 'btn-link',
}
